services:
  - type: web
    name: zerodha-backend
    env: node
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 5000
